
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jose
 */
public class Aditivo extends javax.swing.JFrame {

    /**
     * Creates new form Aditivo
     */
    double x;
    double x1;
    double x2;
    double x3;
    double x4;
    double x5;
    double m;
    public static DefaultTableModel tabla;

    public Aditivo() {
        initComponents();
        
        tabla = new DefaultTableModel();
        tabla.addColumn("X");
        tabla.addColumn("X/m");
        this.Resultadosvvv.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lista = new javax.swing.JComboBox<>();
        Cvvv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Mvvv = new javax.swing.JTextField();
        Pruebasvvv = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultadosvvv = new javax.swing.JTable();
        Xvvv = new javax.swing.JTextField();
        Avvv = new javax.swing.JTextField();
        corrervvv = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Bvvv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Exportarvvv = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        X5vvv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promedio", "Frecuencia", "Kolmogorov-smirnov", "Corridas", "Serie" }));

        Cvvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Cvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CvvvActionPerformed(evt);
            }
        });

        jLabel4.setText("m");

        Mvvv.setPreferredSize(new java.awt.Dimension(70, 22));

        Pruebasvvv.setText("Realizar pruebas");
        Pruebasvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PruebasvvvActionPerformed(evt);
            }
        });

        Resultadosvvv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Resultadosvvv.setEnabled(false);
        jScrollPane1.setViewportView(Resultadosvvv);

        Xvvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Xvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XvvvActionPerformed(evt);
            }
        });

        Avvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Avvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvvvActionPerformed(evt);
            }
        });

        corrervvv.setText("correr");
        corrervvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrervvvActionPerformed(evt);
            }
        });

        jLabel6.setText("x3");

        jLabel1.setText("X");

        Bvvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Bvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvvvActionPerformed(evt);
            }
        });

        jLabel5.setText("GENERADOR CONGRUENCIAL MIXTO");

        jLabel2.setText("x2");

        jLabel3.setText("x4");

        Exportarvvv.setText("Exportar a Excel");
        Exportarvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarvvvActionPerformed(evt);
            }
        });

        jLabel7.setText("x5");

        X5vvv.setPreferredSize(new java.awt.Dimension(70, 22));
        X5vvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X5vvvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(45, 45, 45)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Xvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Avvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(42, 42, 42)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Mvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(corrervvv))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(Bvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(Cvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(X5vvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel7)))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pruebasvvv)
                .addGap(51, 51, 51)
                .addComponent(Exportarvvv)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Xvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Avvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(X5vvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(Mvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(corrervvv))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exportarvvv)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pruebasvvv)
                        .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CvvvActionPerformed

    private void PruebasvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PruebasvvvActionPerformed
        // TODO add your handling code here:
        int index = Lista.getSelectedIndex();
        if(index == 0){
            Promedio newframe = new Promedio();
            newframe.setVisible(true);
            Promedio.tipo = "Aditivo";
        }
        if(index == 1){
            Frecuencia newframe = new Frecuencia();
            newframe.setVisible(true);
            Frecuencia.tipo = "Aditivo";
        }
        if(index == 2){
            Smirnov newframe = new Smirnov();
            newframe.setVisible(true);
            Smirnov.tipo = "Aditivo";
            Smirnov.m = m;
        }
        if(index == 3){
            Corridas newframe = new Corridas();
            newframe.setVisible(true);
            Corridas.tipo = "Aditivo";
        }
        if(index == 4){
            Serie newframe = new Serie();
            newframe.setVisible(true);
            Serie.tipo = "Aditivo";
        }
    }//GEN-LAST:event_PruebasvvvActionPerformed

    private void XvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XvvvActionPerformed

    private void AvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvvvActionPerformed

    private void corrervvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrervvvActionPerformed
        // TODO add your handling code here:
        while(tabla.getRowCount()>0){
            tabla.removeRow(0);
        }

        x = Double.parseDouble( Xvvv.getText());
        x2 = Double.parseDouble( Avvv.getText());
        x3 = Double.parseDouble( Bvvv.getText());
        x4 = Double.parseDouble( Cvvv.getText());
        x5 = Double.parseDouble( X5vvv.getText());
        m = Double.parseDouble( Mvvv.getText());

        double xn;
        int contador = 0, i = 0;
        double[] arreglo = new double[(int)m + 5];
        arreglo[0] = x;
        arreglo[1] = x2;
        arreglo[2] = x3;
        arreglo[3] = x4;
        arreglo[4] = x5;
        /*       double primer_numero = 0;
        double[] N_aleatorios_m = new double[m];
        double[] N = new double[m];*/

        while (i < m){
            arreglo[i + 5] = (arreglo[i] + arreglo[i + 4]) % m;
            xn = arreglo[i+5];

            contador++;
            i++;
            tabla.addRow(new Object[]{xn,xn/m});
        } 
    }//GEN-LAST:event_corrervvvActionPerformed

    private void BvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BvvvActionPerformed

    private void X5vvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X5vvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_X5vvvActionPerformed

    private void ExportarvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarvvvActionPerformed
        // TODO add your handling code here:
        ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(Resultadosvvv);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al exportar"+ex);
        }
    }//GEN-LAST:event_ExportarvvvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aditivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aditivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aditivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aditivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aditivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Avvv;
    private javax.swing.JTextField Bvvv;
    private javax.swing.JTextField Cvvv;
    private javax.swing.JButton Exportarvvv;
    private javax.swing.JComboBox<String> Lista;
    private javax.swing.JTextField Mvvv;
    private javax.swing.JButton Pruebasvvv;
    private javax.swing.JTable Resultadosvvv;
    private javax.swing.JTextField X5vvv;
    private javax.swing.JTextField Xvvv;
    private javax.swing.JButton corrervvv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
