
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jose
 */
public class Corridas extends javax.swing.JFrame {

    /**
     * Creates new form Corridas
     */
    public static String tipo;
    public static DefaultTableModel tabla;
    public Corridas() {
        initComponents();
        this.setLocationRelativeTo(null);   
        tabla = new DefaultTableModel();
        tabla.addColumn("U");
        tabla.addColumn("var");
        tabla.addColumn("z");
        tabla.addColumn("chi");
        this.Resultadosvvv.setModel(tabla);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salida1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultadosvvv = new javax.swing.JTable();
        Calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Salida = new javax.swing.JTextField();
        Exportarvvv = new javax.swing.JButton();

        Salida1.setPreferredSize(new java.awt.Dimension(70, 22));
        Salida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salida1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Resultadosvvv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Resultadosvvv.setEnabled(false);
        jScrollPane1.setViewportView(Resultadosvvv);

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        jLabel1.setText("PRUEBA DE CORRIDAS");

        Salida.setPreferredSize(new java.awt.Dimension(70, 22));
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        Exportarvvv.setText("Exportar a Excel");
        Exportarvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarvvvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Exportarvvv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Exportarvvv)
                        .addGap(18, 18, 18)
                        .addComponent(Calcular)
                        .addGap(18, 18, 18)
                        .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        while(tabla.getRowCount()>0){
            tabla.removeRow(0);
        }

        ArrayList<Double> datos = new ArrayList<>();
        if(tipo == "Mixto"){
            int contador = Mixto.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];
            double[] secuencia = new double[contador];
            int corridas = 0;

            for(int i=0; i<contador; i++){
                Object valores = Mixto.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }

            for(int j=0; j<contador; j++){
                arreglo[j] = datos.get(j);
            }
            for(int s=0; s<contador-1; s++){
                if (arreglo[s + 1] <= arreglo[s]) {
                secuencia[s] = 0;
            } else if (arreglo[s + 1] > arreglo[s]) {
                secuencia[s] = 1;
            }
            }
            for (int l = 0; l < contador - 1; l++) {

            if (secuencia[l + 1] != secuencia[l]) {
                corridas++;
            }
            System.out.println(secuencia[l]);
        }
        float u, var, z;

        u = ((float) (2 * contador) - 1) / 3;
        var = ((float) (16 * contador) - 29) / 90;
        z = (float) Math.abs((corridas - u) / Math.sqrt(var));
            
        tabla.addRow(new Object[]{u, var, z, 1.96});
        if(z<1.96){
            Salida.setText("Correcto");
        }else{
            Salida.setText("Incorrecto");
        }


        }
        if(tipo == "Multiplicativo"){
            int contador = Multiplicativo.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];
            double[] secuencia = new double[contador];
            int corridas = 0;

            for(int i=0; i<contador; i++){
                Object valores = Multiplicativo.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }

            for(int j=0; j<contador; j++){
                arreglo[j] = datos.get(j);
            }
            for(int s=0; s<contador-1; s++){
                if (arreglo[s + 1] <= arreglo[s]) {
                secuencia[s] = 0;
            } else if (arreglo[s + 1] > arreglo[s]) {
                secuencia[s] = 1;
            }
            }
            for (int l = 0; l < contador - 1; l++) {

            if (secuencia[l + 1] != secuencia[l]) {
                corridas++;
            }
            System.out.println(secuencia[l]);
        }
        float u, var, z;

        u = ((float) (2 * contador) - 1) / 3;
        var = ((float) (16 * contador) - 29) / 90;
        z = (float) Math.abs((corridas - u) / Math.sqrt(var));
            
        tabla.addRow(new Object[]{u, var, z, 1.96});
        if(z<1.96){
            Salida.setText("Correcto");
        }else{
            Salida.setText("Incorrecto");
        }

        }
        if(tipo == "Fibonacci"){
            int contador = Fibonacci.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];
            double[] secuencia = new double[contador];
            int corridas = 0;

            for(int i=0; i<contador; i++){
                Object valores = Fibonacci.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }

            for(int j=0; j<contador; j++){
                arreglo[j] = datos.get(j);
            }
            for(int s=0; s<contador-1; s++){
                if (arreglo[s + 1] <= arreglo[s]) {
                secuencia[s] = 0;
            } else if (arreglo[s + 1] > arreglo[s]) {
                secuencia[s] = 1;
            }
            }
            for (int l = 0; l < contador - 1; l++) {

            if (secuencia[l + 1] != secuencia[l]) {
                corridas++;
            }
        }
        float u, var, z;
            System.out.println(corridas);
            System.out.println(contador);

        u = ((float) (2 * contador) - 1) / 3;
        var = ((float) (16 * contador) - 29) / 90;
        z = (float) Math.abs((corridas - u) / Math.sqrt(var));
            
        tabla.addRow(new Object[]{u, var, z, 1.96});
        if(z<1.96){
            Salida.setText("Correcto");
        }else{
            Salida.setText("Incorrecto");
        }


        }
        if(tipo == "Cuadratico"){
            int contador = Cuadrático.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];
            double[] secuencia = new double[contador];
            int corridas = 0;

            for(int i=0; i<contador; i++){
                Object valores = Cuadrático.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }

            for(int j=0; j<contador; j++){
                arreglo[j] = datos.get(j);
            }
            for(int s=0; s<contador-1; s++){
                if (arreglo[s + 1] <= arreglo[s]) {
                secuencia[s] = 0;
            } else if (arreglo[s + 1] > arreglo[s]) {
                secuencia[s] = 1;
            }
            }
            for (int l = 0; l < contador - 1; l++) {

            if (secuencia[l + 1] != secuencia[l]) {
                corridas++;
            }
        }
        float u, var, z;
            System.out.println(corridas);
            System.out.println(contador);

        u = ((float) (2 * contador) - 1) / 3;
        var = ((float) (16 * contador) - 29) / 90;
        z = (float) Math.abs((corridas - u) / Math.sqrt(var));
        tabla.addRow(new Object[]{u, var, z, 1.96});
        if(z<1.96){
            Salida.setText("Correcto");
        }else{
            Salida.setText("Incorrecto");
        }


        }
        if(tipo == "Aditivo"){
            int contador = Aditivo.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];
            double[] secuencia = new double[contador];
            int corridas = 0;

            for(int i=0; i<contador; i++){
                Object valores = Aditivo.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }

            for(int j=0; j<contador; j++){
                arreglo[j] = datos.get(j);
            }
            for(int s=0; s<contador-1; s++){
                if (arreglo[s + 1] <= arreglo[s]) {
                secuencia[s] = 0;
            } else if (arreglo[s + 1] > arreglo[s]) {
                secuencia[s] = 1;
            }
            }
            for (int l = 0; l < contador - 1; l++) {

            if (secuencia[l + 1] != secuencia[l]) {
                corridas++;
            }
            System.out.println(secuencia[l]);
        }
        float u, var, z;

        u = ((float) (2 * contador) - 1) / 3;
        var = ((float) (16 * contador) - 29) / 90;
        z = (float) Math.abs((corridas - u) / Math.sqrt(var));
            
        tabla.addRow(new Object[]{u, var, z, 1.96});
        if(z<1.96){
            Salida.setText("Correcto");
        }else{
            Salida.setText("Incorrecto");
        }


        }

    }//GEN-LAST:event_CalcularActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalidaActionPerformed

    private void Salida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salida1ActionPerformed

    private void ExportarvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarvvvActionPerformed
        // TODO add your handling code here:
        ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(Resultadosvvv);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al exportar"+ex);
        }
    }//GEN-LAST:event_ExportarvvvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corridas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Exportarvvv;
    private javax.swing.JTable Resultadosvvv;
    private javax.swing.JTextField Salida;
    private javax.swing.JTextField Salida1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
