
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jose
 */
public class Cuadrático extends javax.swing.JFrame {

    /**
     * Creates new form Cuadrático
     */
    double x;
    double a;
    double b;
    double c;
    double m;
    double x1;
    double a1;
    double b1;
    double c1;
    double m1;
    public static DefaultTableModel tabla;

    public Cuadrático() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tabla = new DefaultTableModel();
        tabla.addColumn("X");
        tabla.addColumn("X/m");
        this.Resultadosvvv.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cvvv = new javax.swing.JTextField();
        Mvvv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultadosvvv = new javax.swing.JTable();
        corrervvv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Exportarvvv = new javax.swing.JButton();
        Lista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Pruebasvvv = new javax.swing.JButton();
        Xvvv = new javax.swing.JTextField();
        Avvv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Bvvv = new javax.swing.JTextField();
        Validas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cvvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Cvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CvvvActionPerformed(evt);
            }
        });

        Mvvv.setPreferredSize(new java.awt.Dimension(70, 22));

        Resultadosvvv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Resultadosvvv.setEnabled(false);
        jScrollPane1.setViewportView(Resultadosvvv);

        corrervvv.setText("correr");
        corrervvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrervvvActionPerformed(evt);
            }
        });

        jLabel1.setText("X");

        jLabel5.setText("GENERADOR CONGRUENCIAL MIXTO");

        jLabel2.setText("A");

        jLabel3.setText("C");

        Exportarvvv.setText("Exportar a Excel");
        Exportarvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarvvvActionPerformed(evt);
            }
        });

        Lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promedio", "Frecuencia", "Kolmogorov-smirnov", "Corridas", "Serie" }));

        jLabel4.setText("m");

        Pruebasvvv.setText("Realizar pruebas");
        Pruebasvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PruebasvvvActionPerformed(evt);
            }
        });

        Xvvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Xvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XvvvActionPerformed(evt);
            }
        });

        Avvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Avvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvvvActionPerformed(evt);
            }
        });

        jLabel6.setText("B");

        Bvvv.setPreferredSize(new java.awt.Dimension(70, 22));

        Validas.setText("Validar");
        Validas.setPreferredSize(new java.awt.Dimension(70, 22));
        Validas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Xvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Avvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Mvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(corrervvv)
                                        .addComponent(Cvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Bvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))
                                    .addComponent(Validas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pruebasvvv)
                .addGap(51, 51, 51)
                .addComponent(Exportarvvv)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Xvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Avvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Bvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Validas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corrervvv))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exportarvvv)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pruebasvvv)
                        .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CvvvActionPerformed

    private void corrervvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrervvvActionPerformed
        // TODO add your handling code here:
        while(tabla.getRowCount()>0){
            tabla.removeRow(0);
        }

        x = Double.parseDouble( Xvvv.getText());
        a = Double.parseDouble( Avvv.getText());
        b = Double.parseDouble( Bvvv.getText());
        m = Double.parseDouble( Mvvv.getText());
        c = Double.parseDouble( Cvvv.getText());

        double xn;
        int contador = 0, i = 0;
        /*       double primer_numero = 0;
        double[] N_aleatorios_m = new double[m];
        double[] N = new double[m];*/

        do {
            xn = ((a * x * x) + (b * x) + c) % m;
            x = xn;

            contador++;
            i++;
            tabla.addRow(new Object[]{xn,xn/m});
            System.out.println(xn);
        } while (i < m);

    }//GEN-LAST:event_corrervvvActionPerformed

    private void PruebasvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PruebasvvvActionPerformed
        // TODO add your handling code here:
        int index = Lista.getSelectedIndex();
        if(index == 0){
            Promedio newframe = new Promedio();
            newframe.setVisible(true);
            Promedio.tipo = "Cuadratico";
        }
        if(index == 1){
            Frecuencia newframe = new Frecuencia();
            newframe.setVisible(true);
            Frecuencia.tipo = "Cuadratico";
        }
        if(index == 2){
            Smirnov newframe = new Smirnov();
            newframe.setVisible(true);
            Smirnov.tipo = "Cuadratico";
            Smirnov.m = m;
        }
        if(index == 3){
            Corridas newframe = new Corridas();
            newframe.setVisible(true);
            Corridas.tipo = "Cuadratico";
        }
        if(index == 4){
            Serie newframe = new Serie();
            newframe.setVisible(true);
            Serie.tipo = "Cuadratico";
        }
    }//GEN-LAST:event_PruebasvvvActionPerformed

    private void XvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XvvvActionPerformed

    private void AvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvvvActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_AvvvActionPerformed

    private void ExportarvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarvvvActionPerformed
        // TODO add your handling code here:
        ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(Resultadosvvv);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al exportar"+ex);
        }
    }//GEN-LAST:event_ExportarvvvActionPerformed

    private void ValidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidasActionPerformed
        // TODO add your handling code here:

        x1 = Double.parseDouble( Xvvv.getText());
        a1 = Double.parseDouble( Avvv.getText());
        b1 = Double.parseDouble( Bvvv.getText());
        m1 = Double.parseDouble( Mvvv.getText());
        c1 = Double.parseDouble( Cvvv.getText());
        
        if (a1 % 2 != 0) {
                        JOptionPane.showMessageDialog(null, "a debe ser número par");
                    }
                    if ((b1 - 1) % 4 != 0) {
                        JOptionPane.showMessageDialog(null, "b no cumple con la ecuación: (b-1)%4 = 0");
                    }
                    if (c1 % 2 == 0) {
                        JOptionPane.showMessageDialog(null, "c debe ser impar");
                    }
                    if (a1 % 2 == 0 && (b1 - 1) % 4 == 0 && c1 % 2 == 1) {
                        JOptionPane.showMessageDialog(null, "Se cumplen todas las condiciones");
                    }
    }//GEN-LAST:event_ValidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuadrático.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuadrático.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuadrático.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuadrático.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuadrático().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Avvv;
    private javax.swing.JTextField Bvvv;
    private javax.swing.JTextField Cvvv;
    private javax.swing.JButton Exportarvvv;
    private javax.swing.JComboBox<String> Lista;
    private javax.swing.JTextField Mvvv;
    private javax.swing.JButton Pruebasvvv;
    private javax.swing.JTable Resultadosvvv;
    private javax.swing.JButton Validas;
    private javax.swing.JTextField Xvvv;
    private javax.swing.JButton corrervvv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
