
import java.io.IOException;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jose
 */
public class Multiplicativo extends javax.swing.JFrame {

    /**
     * Creates new form Multiplicativo
     */
    double x;
    double a;
    double m;
    double x1;
    double a1;
    double m1;
    HashSet<Double> repetido = new HashSet<>();

    public static DefaultTableModel tabla;
    public Multiplicativo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tabla = new DefaultTableModel();
        tabla.addColumn("X");
        tabla.addColumn("X/m");
        this.Resultadosvvv.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mvvv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultadosvvv = new javax.swing.JTable();
        corrervvv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Exportarvvv = new javax.swing.JButton();
        Lista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Pruebasvvv = new javax.swing.JButton();
        Xvvv = new javax.swing.JTextField();
        Avvv = new javax.swing.JTextField();
        Validas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mvvv.setPreferredSize(new java.awt.Dimension(70, 22));

        Resultadosvvv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Resultadosvvv.setEnabled(false);
        jScrollPane1.setViewportView(Resultadosvvv);

        corrervvv.setText("correr");
        corrervvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrervvvActionPerformed(evt);
            }
        });

        jLabel1.setText("X");

        jLabel5.setText("GENERADOR CONGRUENCIAL MULTIPLICATIVO");

        jLabel2.setText("A");

        Exportarvvv.setText("Exportar a Excel");
        Exportarvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarvvvActionPerformed(evt);
            }
        });

        Lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promedio", "Frecuencia", "Kolmogorov-smirnov", "Corridas", "Serie" }));

        jLabel4.setText("m");

        Pruebasvvv.setText("Realizar pruebas");
        Pruebasvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PruebasvvvActionPerformed(evt);
            }
        });

        Xvvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Xvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XvvvActionPerformed(evt);
            }
        });

        Avvv.setPreferredSize(new java.awt.Dimension(70, 22));
        Avvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvvvActionPerformed(evt);
            }
        });

        Validas.setText("Validar");
        Validas.setPreferredSize(new java.awt.Dimension(70, 22));
        Validas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Xvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Avvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(corrervvv)
                            .addComponent(Validas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pruebasvvv)
                .addGap(51, 51, 51)
                .addComponent(Exportarvvv)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Xvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Avvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Mvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(Validas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(corrervvv))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exportarvvv)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pruebasvvv)
                        .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvvvActionPerformed

    private void corrervvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrervvvActionPerformed
        // TODO add your handling code here:
        while(tabla.getRowCount()>0){
            tabla.removeRow(0);
        }

        x = Double.parseDouble( Xvvv.getText());
        a = Double.parseDouble( Avvv.getText());
        m = Double.parseDouble( Mvvv.getText());

        double xn;
        int contador = 0, i = 0;
        /*       double primer_numero = 0;
        double[] N_aleatorios_m = new double[m];
        double[] N = new double[m];*/
        do {
            x = (a * x) % m;
            xn = x/m;
            
            if(repetido.contains(x)){
                break;
            }
            repetido.add(x);

            contador++;
            i++;
            tabla.addRow(new Object[]{(int)x,xn});
            System.out.println(xn);
        } while (i < m);
    }//GEN-LAST:event_corrervvvActionPerformed

    private void PruebasvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PruebasvvvActionPerformed
        // TODO add your handling code here:
        int index = Lista.getSelectedIndex();
        if(index == 0){
            Promedio newframe = new Promedio();
            newframe.setVisible(true);
            Promedio.tipo = "Multiplicativo";
        }
        if(index == 1){
            Frecuencia newframe = new Frecuencia();
            newframe.setVisible(true);
            Frecuencia.tipo = "Multiplicativo";
        }
        if(index == 2){
            Smirnov newframe = new Smirnov();
            newframe.setVisible(true);
            Smirnov.tipo = "Multiplicativo";
            Smirnov.m = m;
        }
        if(index == 3){
            Corridas newframe = new Corridas();
            newframe.setVisible(true);
            Corridas.tipo = "Multiplicativo";
        }
        if(index == 4){
            Serie newframe = new Serie();
            newframe.setVisible(true);
            Serie.tipo = "Multiplicativo";
        }
    }//GEN-LAST:event_PruebasvvvActionPerformed

    private void XvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XvvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XvvvActionPerformed

    private void ExportarvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarvvvActionPerformed
        // TODO add your handling code here:
        ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(Resultadosvvv);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al exportar"+ex);
        }
    }//GEN-LAST:event_ExportarvvvActionPerformed
    public static int calcularMCD(double a, double b) {
        while (b != 0) {
            int temp = (int) b;
            b = a % b;
            a = temp;
        }
        return (int) a;
    }

    public static boolean sonRelativamentePrimos(double a, double b) {
        int mcd = calcularMCD(a, b);
        return mcd == 1;
    }
    private void ValidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidasActionPerformed
        // TODO add your handling code here:

        x1 = Double.parseDouble( Xvvv.getText());
        a1 = Double.parseDouble( Avvv.getText());
        m1 = Double.parseDouble( Mvvv.getText());
                    if (x1 % 2 == 0) {
                        JOptionPane.showMessageDialog(null, "La semilla debe ser impar");
                    }

                    if (!sonRelativamentePrimos(x1, m1)) {
                        JOptionPane.showMessageDialog(null, "m y la semilla no son relativamente primos");
                    }

                    if (((a1 + 3) / 8) % 1 != 0 || ((a1 - 3) / 8) % 1 != 0) {
                        JOptionPane.showMessageDialog(null, "a no cumple con la excuación 8t ± 3");
                    }

                    if (x1 % 2 != 0 && sonRelativamentePrimos(x1, m1) && (((a1 + 3) / 8) % 1 == 0 || ((a1 - 3) / 8) % 1 == 0)) {
                        JOptionPane.showMessageDialog(null, "Todo correcto");
                    }
        
    }//GEN-LAST:event_ValidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Multiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Multiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Multiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Multiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multiplicativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Avvv;
    private javax.swing.JButton Exportarvvv;
    private javax.swing.JComboBox<String> Lista;
    private javax.swing.JTextField Mvvv;
    private javax.swing.JButton Pruebasvvv;
    private javax.swing.JTable Resultadosvvv;
    private javax.swing.JButton Validas;
    private javax.swing.JTextField Xvvv;
    private javax.swing.JButton corrervvv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
