
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jose
 */
public class Smirnov extends javax.swing.JFrame {

    /**
     * Creates new form Smirnov
     */
    public static String tipo;
    public static Double m;
    public static DefaultTableModel tabla;

    public Smirnov() {
        initComponents();
        this.setLocationRelativeTo(null);   
        tabla = new DefaultTableModel();
        tabla.addColumn("indice");
        tabla.addColumn("xn/m");
        tabla.addColumn("indice/m-1");
        tabla.addColumn("|diferencia|");
        tabla.addColumn("MAX");
        tabla.addColumn("chi");
        this.Resultadosvvv.setModel(tabla);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Resultadosvvv = new javax.swing.JTable();
        Calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Salida = new javax.swing.JTextField();
        Exportarvvv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Resultadosvvv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Resultadosvvv.setEnabled(false);
        jScrollPane1.setViewportView(Resultadosvvv);

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        jLabel1.setText("PRUEBA DE SMIRNOV");

        Salida.setPreferredSize(new java.awt.Dimension(70, 22));
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        Exportarvvv.setText("Exportar a Excel");
        Exportarvvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarvvvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calcular)
                    .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exportarvvv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(Exportarvvv)
                        .addGap(18, 18, 18)
                        .addComponent(Calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        while(tabla.getRowCount()>0){
            tabla.removeRow(0);
        }
        

        ArrayList<Double> datos = new ArrayList<>();
        if(tipo == "Mixto"){
            int contador = Mixto.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];

            for(int i=0; i<contador; i++){
                Object valores = Mixto.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }
            
            Collections.sort(datos);

           for (int a = 0; a < contador; a++) {
                arreglo[a] = Math.abs(((double) (a + 1) / (double) (m - 1)) - datos.get(a));
                
            }
           double mayor = 0;
            for (int s = 0; s < contador; s++) {

                if (arreglo[s] > mayor) {
                    mayor = arreglo[s];
                }
            }
            for(int j=0; j<contador; j++){
            tabla.addRow(new Object[]{j+1,datos.get(j), (j+1)/(m-1),arreglo[j],mayor,1.36 / Math.sqrt(m - 1)});    
            }
            if(mayor  <=  1.36 / Math.sqrt(m - 1)){
                Salida.setText("Correcto");
            }else{
                Salida.setText("Incorrecto");
            }

        }
        if(tipo == "Multiplicativo"){
            int contador = Multiplicativo.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];

            for(int i=0; i<contador; i++){
                Object valores = Multiplicativo.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }
            
            Collections.sort(datos);

           for (int a = 0; a < contador; a++) {
                arreglo[a] = Math.abs(((double) (a + 1) / (double) (m - 1)) - datos.get(a));
                
            }
           double mayor = 0;
            for (int s = 0; s < contador; s++) {

                if (arreglo[s] > mayor) {
                    mayor = arreglo[s];
                }
            }
            for(int j=0; j<contador; j++){
            tabla.addRow(new Object[]{j+1,datos.get(j), (j+1)/(m-1),arreglo[j],mayor,1.36 / Math.sqrt(m - 1)});
                
            }
            if(mayor  <=  1.36 / Math.sqrt(m - 1)){
                Salida.setText("Correcto");
            }else{
                Salida.setText("Incorrecto");
            }

        }
        if(tipo == "Fibonacci"){
            int contador = Fibonacci.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];

            for(int i=0; i<contador; i++){
                Object valores = Fibonacci.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }
            
            Collections.sort(datos);

           for (int a = 0; a < contador; a++) {
                arreglo[a] = Math.abs(((double) (a + 1) / (double) (m - 1)) - datos.get(a));
                
            }
           double mayor = 0;
            for (int s = 0; s < contador; s++) {

                if (arreglo[s] > mayor) {
                    mayor = arreglo[s];
                }
            }
            for(int j=0; j<contador; j++){
            tabla.addRow(new Object[]{j+1,datos.get(j), (j+1)/(m-1),arreglo[j],mayor,1.36 / Math.sqrt(m - 1)});
                
            }
            if(mayor  <=  1.36 / Math.sqrt(m - 1)){
                Salida.setText("Correcto");
            }else{
                Salida.setText("Incorrecto");
            }

        }
        if(tipo == "Cuadratico"){
            int contador = Cuadrático.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];

            for(int i=0; i<contador; i++){
                Object valores = Cuadrático.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }
            
            Collections.sort(datos);

           for (int a = 0; a < contador; a++) {
                arreglo[a] = Math.abs(((double) (a + 1) / (double) (m - 1)) - datos.get(a));
                
            }
           double mayor = 0;
            for (int s = 0; s < contador; s++) {

                if (arreglo[s] > mayor) {
                    mayor = arreglo[s];
                }
            }
            for(int j=0; j<contador; j++){
            tabla.addRow(new Object[]{j+1,datos.get(j), (j+1)/(m-1),arreglo[j],mayor,1.36 / Math.sqrt(m - 1)});
                
            }
            if(mayor  <=  1.36 / Math.sqrt(m - 1)){
                Salida.setText("Correcto");
            }else{
                Salida.setText("Incorrecto");
            }

        }
        if(tipo == "Aditivo"){
            int contador = Aditivo.tabla.getRowCount();
            double[] arreglo = new double[(int)contador];

            for(int i=0; i<contador; i++){
                Object valores = Aditivo.tabla.getValueAt(i, 1);
                double convertir = Double.parseDouble(valores.toString());
                datos.add(convertir);
            }
            
            Collections.sort(datos);

           for (int a = 0; a < contador; a++) {
                arreglo[a] = Math.abs(((double) (a + 1) / (double) (m - 1)) - datos.get(a));
                
            }
           double mayor = 0;
            for (int s = 0; s < contador; s++) {

                if (arreglo[s] > mayor) {
                    mayor = arreglo[s];
                }
            }
            for(int j=0; j<contador; j++){
            tabla.addRow(new Object[]{j+1,datos.get(j), (j+1)/(m-1),arreglo[j],mayor,1.36 / Math.sqrt(m - 1)});
                
            }
            if(mayor  <=  1.36 / Math.sqrt(m - 1)){
                Salida.setText("Correcto");
            }else{
                Salida.setText("Incorrecto");
            }

        }
        
    }//GEN-LAST:event_CalcularActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalidaActionPerformed

    private void ExportarvvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarvvvActionPerformed
        // TODO add your handling code here:
        ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(Resultadosvvv);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al exportar"+ex);
        }
    }//GEN-LAST:event_ExportarvvvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Smirnov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Smirnov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Smirnov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Smirnov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Smirnov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Exportarvvv;
    private javax.swing.JTable Resultadosvvv;
    private javax.swing.JTextField Salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
